### ISSUE TITLE
Feature: Login

### ISSUE THREAD

**Issue by makreeltje** [smeelfnet/dashboard-spring#1]
### Description
As a user, I'd like to log in, in order to get access to the service.

### Acceptance Criteria
- [ ] The password should show up like dots
- [ ] In case the user forgets their password, they should be able to request a new one using their email

### Tasks
- [x] The user should log in using their email and password
- [x] Both fields should be filled in for a log in to be valid
