### ISSUE TITLE
Feature: Register

### ISSUE THREAD

**Issue by makreeltje** [smeelfnet/dashboard-spring#2]
### Description
As a User, I'd like to register an account, in order to get access to the platform.

### Acceptance Criteria
- [ ] The user can send a request for a register token
- [ ] The user receives their register token via email 

### Tasks
- [ ] The user can only register when they have a valid register token 
- [x] The user can only register when they fill in all the required fields
- [ ] The request for a register token can be accepted or denied
